import { AlertTriangle, ArrowRight, Bot, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Flame, MessageSquareText, MoreHorizontal, PhoneCall, Sparkles, TrendingUp } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { campaignChart, connectionCards, metrics } from '../../data/dashboardData'
import { Badge, Button } from '../common/UI'

export default function DashboardHome({ onNavigate, openAssistant }) {
  return <div className="dashboard-view home-view">
    <section className="owner-brief"><div><span><Sparkles/> OWNER BRIEF · SUNDAY, 21 JUNE</span><h2>Revenue is up. Three conversations need a human.</h2><p>AI handled 68% of routine questions while your team focused on 94 high-intent buyers.</p></div><div><Button onClick={openAssistant}>Open AI brief <ArrowRight/></Button><Button variant="secondary" onClick={()=>onNavigate('inbox')}>Review urgent chats</Button></div></section>
    <section className="metric-grid">{metrics.map(m=><article className="metric-card" key={m.label}><header><span className={`metric-icon icon-${m.tone}`}><m.icon/></span><MoreHorizontal/></header><p>{m.label}</p><h3>{m.value}</h3><small>{m.change}</small></article>)}</section>
    <section className="status-grid">{connectionCards.map((c,i)=><article key={c.name}><span className={`status-icon s${i}`}><c.icon/></span><div><p>{c.name}</p><b>{c.status}</b><small>{c.detail}</small></div><i/></article>)}</section>
    <div className="home-main-grid">
      <section className="panel chart-panel"><PanelHead title="Campaign performance" copy="Sent vs replies · last 7 days" action="View analytics"/><div className="chart-legend"><span><i className="sent"/> Sent</span><span><i className="replies"/> Replies</span></div><div className="campaign-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={campaignChart}><defs><linearGradient id="sentFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#15b87a" stopOpacity={.3}/><stop offset="100%" stopColor="#15b87a" stopOpacity={0}/></linearGradient><linearGradient id="replyFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7c5cff" stopOpacity={.22}/><stop offset="100%" stopColor="#7c5cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#dbe3df"/><XAxis dataKey="day" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #dfe8e3',fontSize:12}}/><Area type="monotone" dataKey="sent" stroke="#15b87a" strokeWidth={2.5} fill="url(#sentFill)"/><Area type="monotone" dataKey="replies" stroke="#7c5cff" strokeWidth={2.5} fill="url(#replyFill)"/></AreaChart></ResponsiveContainer></div><footer className="chart-summary"><div><b>6,540</b><span>messages sent</span></div><div><b>2,110</b><span>customers read</span></div><div><b>19.4%</b><span>reply rate</span></div></footer></section>
      <section className="panel alerts-panel"><PanelHead title="Urgent attention" copy="Ranked by opportunity and risk" action="Smart Inbox" onAction={()=>onNavigate('inbox')}/><div className="urgent-list"><UrgentItem icon={CircleDollarSign} tone="red" title="Verify Rahul’s payment" copy="₹24,500 · screenshot received" time="2m" badge="High risk"/><UrgentItem icon={Flame} tone="orange" title="Priya is ready to visit" copy="Bridal lead · score 91" time="8m" badge="Hot lead"/><UrgentItem icon={AlertTriangle} tone="amber" title="Amit needs an order update" copy="Frustrated · delayed 4 days" time="14m" badge="Escalated"/><UrgentItem icon={Clock3} tone="sky" title="6 follow-ups are overdue" copy="Potential value · ₹1.8L" time="Today" badge="Due now"/></div></section>
      <section className="panel activity-panel"><PanelHead title="Recent customer activity" copy="Live across all connected channels" action="See all"/><div className="activity-timeline"><Activity icon={MessageSquareText} title="Priya asked for bridal pricing" copy="Intent: Price + Store visit" time="Now"/><Activity icon={CheckCircle2} title="Order #WAX-1046 marked ready" copy="Sana Khan · WhatsApp order" time="6m"/><Activity icon={PhoneCall} title="Meera booked a callback" copy="Assigned to Kavita" time="18m"/><Activity icon={Bot} title="AI resolved a catalogue query" copy="Safe auto-reply · 94% confidence" time="26m"/></div></section>
      <section className="panel pipeline-panel"><PanelHead title="Lead pipeline" copy="₹14.8L influenced by conversations" action="View contacts" onAction={()=>onNavigate('contacts')}/><div className="pipeline"><Pipeline label="New enquiries" value="286" width="100%" tone="emerald"/><Pipeline label="Qualified" value="164" width="76%" tone="teal"/><Pipeline label="Store visits" value="78" width="54%" tone="violet"/><Pipeline label="Order intent" value="46" width="36%" tone="amber"/></div><div className="pipeline-note"><TrendingUp/><p><b>18.2% better conversion</b><span>than your previous 30 days</span></p></div></section>
    </div>
  </div>
}

function PanelHead({title,copy,action,onAction}){return <header className="panel-head"><div><h3>{title}</h3><p>{copy}</p></div><button onClick={onAction}>{action}<ChevronRight/></button></header>}
function UrgentItem({icon:Icon,tone,title,copy,time,badge}){return <article><span className={`urgent-icon ${tone}`}><Icon/></span><div><b>{title}</b><p>{copy}</p><Badge tone={tone==='red'?'rose':tone==='orange'?'amber':'slate'}>{badge}</Badge></div><time>{time}</time><ChevronRight/></article>}
function Activity({icon:Icon,title,copy,time}){return <article><span><Icon/></span><div><b>{title}</b><p>{copy}</p></div><time>{time}</time></article>}
function Pipeline({label,value,width,tone}){return <div><p><span>{label}</span><b>{value}</b></p><span><i className={tone} style={{width}}/></span></div>}
