import { AlertTriangle, ArrowLeft, Bot, CalendarPlus, Check, CheckCheck, ChevronDown, CircleUserRound, Filter, Flame, MoreHorizontal, Paperclip, Phone, Search, Send, Smile, Sparkles, UserRoundCheck, X, Zap } from 'lucide-react'
import { useMemo, useState } from 'react'
import { chatHistories, customers } from '../../data/dashboardData'
import { Badge, Button, useToast } from '../common/UI'

const toneFor = (value) => value === 'Positive' ? 'emerald' : value === 'Frustrated' ? 'rose' : value === 'hot' ? 'rose' : value === 'urgent' ? 'amber' : 'slate'

export default function SmartInbox(){
  const [selectedId,setSelectedId]=useState(1); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('priority'); const [draft,setDraft]=useState(''); const [sent,setSent]=useState({}); const [aiOpen,setAiOpen]=useState(false); const [mobileChatOpen,setMobileChatOpen]=useState(false); const [alert,setAlert]=useState(true); const toast=useToast()
  const customer=customers.find(c=>c.id===selectedId)
  const visible=useMemo(()=>customers.filter(c=>(filter==='all'||filter==='priority'&&['hot','urgent'].includes(c.priority)||filter===c.priority)&&(`${c.name} ${c.message}`.toLowerCase().includes(query.toLowerCase()))),[filter,query])
  const messages=[...(chatHistories[selectedId]||[]),...(sent[selectedId]||[])]
  const send=()=>{if(!draft.trim())return;setSent(prev=>({...prev,[selectedId]:[...(prev[selectedId]||[]),['agent',draft.trim()]]}));setDraft('');toast('Message sent',`${customer.name}’s conversation is up to date`)}
  return <div className={`smart-inbox ${mobileChatOpen?'mobile-chat-open':''}`}>
    <aside className="inbox-list-pane"><header><div><b>Smart Inbox</b><Badge tone="emerald">12 priority</Badge></div><button><Filter/></button></header><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations"/></label><div className="inbox-filters">{['priority','all','hot','urgent'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="customer-list">{visible.map(c=><button key={c.id} className={selectedId===c.id?'active':''} onClick={()=>{setSelectedId(c.id);setMobileChatOpen(true)}}><span className={`customer-avatar avatar-${c.priority}`}>{c.initials}<i/></span><div><div><b>{c.name}</b><time>{c.time}</time></div><p>{c.message}</p><footer><Badge tone={toneFor(c.priority)}>{c.intent}</Badge><span className={`sentiment ${c.sentiment.toLowerCase()}`}>{c.sentiment}</span><em>{c.score}</em>{c.unread>0&&<strong>{c.unread}</strong>}</footer></div></button>)}</div></aside>
    <section className="active-chat"><header><button className="mobile-back" onClick={()=>setMobileChatOpen(false)}><ArrowLeft/></button><span className={`customer-avatar avatar-${customer.priority}`}>{customer.initials}<i/></span><div><b>{customer.name}</b><p>Online on WhatsApp · {customer.intent}</p></div><div><button><Phone/></button><button><CircleUserRound/></button><button onClick={()=>setAiOpen(true)}><Sparkles/></button><button><MoreHorizontal/></button></div></header><div className="chat-thread">{messages.map((m,i)=>m[0]==='system'?<div className="inline-ai-event" key={i}><span><AlertTriangle/></span><div><b>{m[1]}</b><p>Whalexy has paused automation for this conversation.</p></div></div>:<div className={`chat-bubble ${m[0]}`} key={i}><p>{m[1]}</p><span>{m[0]==='customer'?customer.name:`Aman · ${i+10}:4${i}`} {m[0]==='agent'&&<CheckCheck/>}</span></div>)}{alert&&customer.risk==='High'&&<div className="escalation-alert"><AlertTriangle/><div><b>Human attention recommended</b><p>This message includes payment or complaint risk.</p></div><button onClick={()=>setAlert(false)}><X/></button></div>}</div><div className="chat-composer"><div className="quick-actions"><button onClick={()=>setDraft(customer.replies[0])}><Sparkles/> Generate reply</button><button onClick={()=>toast('Assigned to Kavita','Sales Lead notified')}><UserRoundCheck/> Assign agent</button><button onClick={()=>toast('Marked as hot lead','Added to your priority segment')}><Flame/> Mark hot</button><button onClick={()=>toast('Follow-up added','Tomorrow at 11:00 AM')}><CalendarPlus/> Follow-up</button></div><label><button><Paperclip/></button><textarea rows="2" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')send()}} placeholder="Type a WhatsApp reply..."/><button><Smile/></button><Button onClick={send}><Send/> Send</Button></label><small>⌘ + Enter to send · AI suggestions require your review</small></div></section>
    <aside className={`inbox-ai ${aiOpen?'mobile-open':''}`}><header><div><span><Sparkles/></span><p><b>AI Intelligence</b><small>Updated just now</small></p></div><button onClick={()=>setAiOpen(false)}><X/></button></header><div className="ai-scroll"><div className="signal-grid"><Signal label="Intent" value={customer.intent}/><Signal label="Sentiment" value={customer.sentiment} tone={toneFor(customer.sentiment)}/><Signal label="Urgency" value={customer.urgency} tone={customer.urgency==='Urgent'?'rose':'amber'}/><Signal label="Risk level" value={customer.risk} tone={customer.risk==='High'?'rose':'emerald'}/></div><section className="lead-score"><div><strong>{customer.score}</strong><span>/ 100</span></div><p><b>{customer.score>80?'Hot lead':'Warm lead'}</b><small>Price, engagement and intent signals</small></p><Zap/></section><Insight title="Conversation summary"><p>{customer.summary}</p></Insight><Insight title="Next best action"><div className="best-action"><span><Bot/></span><p>{customer.risk==='High'?'Assign a human to verify the sensitive context and reply with a clear resolution time.':'Share the most relevant catalogue and confirm a specific next step.'}</p></div></Insight><Insight title="Suggested replies">{customer.replies.map((r,i)=><div className="suggested-reply" key={r}><p>{r}</p><footer><button onClick={()=>setDraft(r)}>Use reply</button><button onClick={()=>{setDraft(r);toast('Reply ready to edit')}}>Edit</button>{i===0&&<Badge tone="emerald">Best match</Badge>}</footer></div>)}</Insight><section className="eligibility"><p><Check/> Auto-reply eligibility</p><b>{customer.risk==='Low'?'Eligible with review':'Not eligible'}</b><small>{customer.risk==='Low'?'High confidence, no sensitive content':'Sensitive intent requires a human'}</small></section><Button variant="danger" className="w-full" onClick={()=>{setAlert(true);toast('Human escalation created','Owner notified with AI summary')}}><AlertTriangle/> Escalate to human</Button></div></aside>
  </div>
}
function Signal({label,value,tone='slate'}){return <div><small>{label}</small><Badge tone={tone}>{value}</Badge></div>}
function Insight({title,children}){return <section className="ai-insight"><header><b>{title}</b><ChevronDown/></header>{children}</section>}
